#!/usr/bin/env bash

# TODOS:
# - error handling
# - pass params (cert folder, asid) optionally as arg?
# - check uuid is installed

# test/dev asid finchley hospital 200000001772
# test/dev asid barnet 200000001773
# test/dev asid lloyds pharmacy 200000001780
# continuity service dev 200000001613
CERT_FOLDERS=certs
ASID="200000001613"
NHS_NUMBER="9693796381"
REQUEST_BODY_TEMPLATE=$(cat request-body-template.xml)

echo $(echo "${REQUEST_BODY_TEMPLATE/TIMESTAMP_PLACEHOLDER/$(date +"%Y%m%d%H%M%S")}") \
  | echo $(read x; echo "${x//ASID_PLACEHOLDER/${ASID}}") \
  | echo $(read x; echo "${x//NHS_NUMBER_PLACEHOLDER/${NHS_NUMBER}}") \
  | curl -v -k \
  -H "charset: UTF-8" \
  -H "SOAPAction: urn:nhs:names:services:pdsquery/QUPA_IN000008UK02" \
  -H "Content-Type: text/xml" \
  -H "type: text/xml" \
  -H "Correlation-Id: $(uuid)" \
  -H "Message-Id: $(uuid)" \
  -H "Interaction-Id: QUPA_IN000008UK02" \
  -X POST \
  -d "$(</dev/stdin)" \
  --key "$CERT_FOLDERS/key" \
  --cert "$CERT_FOLDERS/cert" \
  --cacert "$CERT_FOLDERS/cacert" \
  https://msg.intspineservices.nhs.uk/sync-service > response-$(date +"%Y%m%d%H%M%S")